# Generated by Django 3.2.12 on 2022-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccessApacheModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(db_index=True, verbose_name='Remote hostname')),
                ('logname', models.CharField(max_length=100, null=True, verbose_name='Remote user')),
                ('user', models.CharField(max_length=100, null=True, verbose_name='Remote user')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='Request time')),
                ('request_line', models.TextField(null=True, verbose_name='First request line')),
                ('status', models.PositiveSmallIntegerField(null=True, verbose_name='Status')),
                ('bytes', models.PositiveIntegerField(null=True, verbose_name='Size response in bytes')),
                ('referer', models.TextField(null=True, verbose_name='Referer')),
                ('user_agent', models.TextField(null=True, verbose_name='User-Agent')),
            ],
        ),
    ]
