# Generated by Django 3.2.12 on 2022-04-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_access_apache', '0003_auto_20220410_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpositioninfilemodel',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data logging'),
        ),
        migrations.AlterField(
            model_name='lastpositioninfilemodel',
            name='path_file',
            field=models.TextField(db_index=True, unique=True, verbose_name='Path file'),
        ),
    ]
