# Generated by Django 3.2.12 on 2022-04-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_access_apache', '0004_auto_20220411_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data logging')),
                ('path_file', models.TextField(db_index=True, unique=True, verbose_name='Path file')),
                ('last_line', models.TextField(blank=True, default='', verbose_name='Last line')),
                ('last_position', models.PositiveBigIntegerField(default=0, verbose_name='Last position')),
            ],
            options={
                'verbose_name': 'File Log',
                'verbose_name_plural': 'File Logs',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='LastPositionInFileModel',
        ),
        migrations.AlterModelOptions(
            name='logaccessapachemodel',
            options={'ordering': ['date', 'host'], 'verbose_name': 'Log Access Apache', 'verbose_name_plural': 'Logs Access Apache'},
        ),
        migrations.AlterField(
            model_name='logaccessapachemodel',
            name='bytes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Size response in bytes'),
        ),
        migrations.AlterField(
            model_name='logaccessapachemodel',
            name='logname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote logname'),
        ),
        migrations.AlterField(
            model_name='logaccessapachemodel',
            name='referer',
            field=models.TextField(blank=True, null=True, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='logaccessapachemodel',
            name='request_line',
            field=models.TextField(blank=True, null=True, verbose_name='First request line'),
        ),
        migrations.AlterField(
            model_name='logaccessapachemodel',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logaccessapachemodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote user'),
        ),
        migrations.AlterField(
            model_name='logaccessapachemodel',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
    ]
